<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\JobVacancy;
use App\Models\User;
use Illuminate\Support\Facades\Hash;

class JobVacancyDemoSeeder extends Seeder
{
    public function run(): void
    {
        // Garantir que temos um usuário admin ou empresa para associar as vagas
        $admin = User::where('email', 'admin@somosunn.com.br')->first();

        if (!$admin) {
            $admin = User::create([
                'name' => 'Admin Somos UNN',
                'email' => 'admin@somosunn.com.br',
                'password' => Hash::make('password'),
                'is_admin' => true,
            ]);
        }

        $vagas = [
            [
                'title' => 'Desenvolvedor Full Stack PHP (Laravel)',
                'company_name' => 'UNN Tecnologia',
                'location' => 'Ribeirão Preto, SP (Híbrido)',
                'type' => 'CLT',
                'level' => 'Pleno',
                'short_description' => 'Buscamos um desenvolvedor apaixonado por código limpo e soluções escaláveis para integrar nosso time core.',
                'description' => '<h3>Sobre a vaga</h3><p>Como Desenvolvedor Full Stack na UNN, você será responsável por manter e evoluir nossa plataforma principal, trabalhando com as tecnologias mais modernas do ecossistema PHP.</p><h3>Responsabilidades</h3><ul><li>Desenvolver novas funcionalidades no frontend e backend</li><li>Otimizar performance de consultas ao banco de dados</li><li>Participar de revisões de código</li><li>Colaborar com o time de Produto</li></ul>',
                'requirements' => '<ul><li>Sólida experiência com PHP 8 e Laravel</li><li>Domínio de JavaScript (Vue.js ou Alpine.js)</li><li>Experiência com Tailwind CSS</li><li>Conhecimento em bancos de dados relacionais (PostgreSQL/MySQL)</li><li>Experiência com Docker e Git</li></ul>',
                'benefits' => '<ul><li>Salário competitivo</li><li>Vale Refeição / Alimentação</li><li>Plano de Saúde e Odontológico</li><li>Horário Flexível</li><li>Participação em lucros e resultados</li></ul>',
                'salary_range' => 'R$ 8.500,00 - R$ 12.000,00',
                'visibility' => 'public',
                'is_active' => true,
                'is_demo' => true,
                'expires_at' => now()->addDays(30),
            ],
            [
                'title' => 'Designer UI/UX Sênior',
                'company_name' => 'Somus Digital',
                'location' => 'Remoto',
                'type' => 'PJ',
                'level' => 'Sênior',
                'short_description' => 'Procuramos um designer com olhar crítico para criar interfaces incríveis e jornadas de usuário simplificadas.',
                'description' => '<h3>O desafio</h3><p>Sua missão será transformar problemas complexos em soluções de design elegantes e intuitivas, garantindo a melhor experiência para os usuários finais.</p><h3>O que você fará</h3><ul><li>Criar wireframes e protótipos de alta fidelidade</li><li>Realizar testes de usabilidade</li><li>Manter e evoluir nosso Design System</li><li>Trabalhar próximo aos desenvolvedores para garantir a fidelidade visual</li></ul>',
                'requirements' => '<ul><li>Mínimo de 5 anos de experiência em Web/Mobile Design</li><li>Domínio do Figma</li><li>Portfólio com casos de estudo reais</li><li>Facilidade de comunicação e trabalho em equipe</li><li>Desejável conhecimento de HTML/CSS (capacidade técnica)</li></ul>',
                'benefits' => '<ul><li>Trabalho 100% Remoto</li><li>Auxílio Home Office</li><li>Ambiente de aprendizado contínuo</li><li>Bonificação anual por metas</li></ul>',
                'salary_range' => 'R$ 10.000,00 - R$ 14.000,00',
                'visibility' => 'public',
                'is_active' => true,
                'is_demo' => true,
                'expires_at' => now()->addDays(45),
            ],
            [
                'title' => 'Gestor de Tráfego Pago',
                'company_name' => 'Agência Performance Max',
                'location' => 'São Paulo, SP (Presencial)',
                'type' => 'CLT',
                'level' => 'Pleno',
                'short_description' => 'Especialista em anúncios (Facebook, Google e TikTok Ads) para escala de infoprodutos e e-commerce.',
                'description' => '<h3>Missão</h3><p>Gerenciar grandes orçamentos diários garantindo o menor CPA possível e o maior ROAS do mercado.</p><h3>Atividades</h3><ul><li>Criação e gestão de campanhas</li><li>Análise profunda de métricas</li><li>Copy para anúncios</li><li>Planejamento estratégico de mídia</li></ul>',
                'requirements' => '<ul><li>Experiência comprovada com Google Ads e FacebookAds</li><li>Domínio de Google Analytics e Tag Manager</li><li>Foco total em resultados (Data-driven)</li><li>Excel Avançado / Dashboards</li></ul>',
                'benefits' => '<ul><li>Vale Refeição de R$ 35/dia</li><li>Vale Transporte</li><li>Seguro de Vida</li><li>Bônus por performance de escala</li></ul>',
                'salary_range' => 'R$ 5.000,00 + Comissões',
                'visibility' => 'public',
                'is_active' => true,
                'is_demo' => true,
                'expires_at' => now()->addDays(20),
            ],
            [
                'title' => 'Social Media & Copywriter',
                'company_name' => 'Inova Marketing',
                'location' => 'Curitiba, PR (Híbrido)',
                'type' => 'Freelance',
                'level' => 'Júnior',
                'short_description' => 'Procuro freelancer para gestão de 3 perfis de clientes premium com foco em engajamento e branding.',
                'description' => '<h3>Sobre o job</h3><p>Planejamento mensal de conteúdo estratégico para redes sociais (Instagram, LinkedIn e Twitter).</p><h3>Entregas esperadas</h3><ul><li>Calendário editorial mensal</li><li>Criação de legendas persuasivas (Copy)</li><li>Roteiros para Reels/TikTok</li><li>Relatório mensal de insights</li></ul>',
                'requirements' => '<ul><li>Portfólio de cases em redes sociais</li><li>Excelente escrita em português</li><li>Criatividade aflorada</li><li>Experiência com Canva ou Adobe Express</li></ul>',
                'benefits' => '<ul><li>Pagamento pontual</li><li>Acesso a cursos de especialização</li><li>Possibilidade de contrato fixo a longo prazo</li></ul>',
                'salary_range' => 'R$ 2.500,00 / mês',
                'visibility' => 'public',
                'is_active' => true,
                'is_demo' => true,
                'expires_at' => now()->addDays(15),
            ],
            [
                'title' => 'Gerente de E-commerce',
                'company_name' => 'Fashion Store',
                'location' => 'Rio de Janeiro, RJ',
                'type' => 'CLT',
                'level' => 'Sênior',
                'short_description' => 'Responsável por toda a operação de venda online, desde o estoque até a entrega final e pós-venda.',
                'description' => '<h3>Objetivo</h3><p>Gerenciar a plataforma de e-commerce, focando no aumento da taxa de conversão e ticket médio.</p>',
                'requirements' => '<ul><li>Experiência com VTEX ou Shopify</li><li>Conhecimento em logística de e-commerce</li><li>Visão de negócios e ROI</li></ul>',
                'benefits' => '<ul><li>Salário + Bônus sobre vendas</li><li>Plano de carreira</li></ul>',
                'salary_range' => 'A combinar',
                'visibility' => 'public',
                'is_active' => true,
                'is_demo' => true,
                'expires_at' => now()->addDays(30),
            ],
            [
                'title' => 'Analista de Suporte ao Cliente',
                'company_name' => 'SaaS Solutions',
                'location' => 'Remoto',
                'type' => 'CLT',
                'level' => 'Pleno',
                'short_description' => 'Procuramos alguém com excelente comunicação para encantar nossos clientes e resolver problemas técnicos.',
                'description' => '<h3>O que você fará</h3><p>Atender clientes via chat, e-mail e telefone, resolvendo dúvidas sobre o uso da plataforma.</p>',
                'requirements' => '<ul><li>Experiência com Zendesk ou similares</li><li>Pacote Office</li><li>Boa escrita</li></ul>',
                'benefits' => '<ul><li>Internet paga pela empresa</li><li>Auxílio saúde</li></ul>',
                'salary_range' => 'R$ 3.800,00',
                'visibility' => 'public',
                'is_active' => true,
                'is_demo' => true,
                'expires_at' => now()->addDays(20),
            ],
            [
                'title' => 'Vendedor Interno B2B',
                'company_name' => 'Distribuidora Global',
                'location' => 'Belo Horizonte, MG (Presencial)',
                'type' => 'CLT',
                'level' => 'Júnior',
                'short_description' => 'Foco em prospecção ativa de novos parceiros comerciais e manutenção da carteira existente.',
                'description' => '<h3>Atividades</h3><ul><li>Cold calls e cold mail</li><li>Apresentação de propostas comerciais</li><li>Registro em CRM (Pipedrive)</li></ul>',
                'requirements' => '<ul><li>Experiência em vendas B2B</li><li>Resiliência e foco em metas</li></ul>',
                'benefits' => '<ul><li>Comissão agressiva</li><li>Vale transporte e alimentação</li></ul>',
                'salary_range' => 'R$ 2.200,00 + Comissões',
                'visibility' => 'public',
                'is_active' => true,
                'is_demo' => true,
                'expires_at' => now()->addDays(25),
            ],
            [
                'title' => 'Desenvolvedor Frontend Vue.js',
                'company_name' => 'SoftHouse XP',
                'location' => 'Florianópolis, SC (Híbrido)',
                'type' => 'PJ',
                'level' => 'Pleno',
                'short_description' => 'Venha construir interfaces modernas e performáticas utilizando Vue 3 e Composition API.',
                'description' => '<h3>Requisitos Técnicos</h3><p>Trabalhar em componentes reutilizáveis e integração com APIs REST.</p>',
                'requirements' => '<ul><li>Vue.js 3</li><li>TypeScript</li><li>Pinia/Vuex</li></ul>',
                'benefits' => '<ul><li>Cursos e eventos pagos</li><li>Day off no aniversário</li></ul>',
                'salary_range' => 'R$ 7.000,00 - R$ 9.500,00',
                'visibility' => 'public',
                'is_active' => true,
                'is_demo' => true,
                'expires_at' => now()->addDays(40),
            ],
            [
                'title' => 'Copywriter para Infoprodutos',
                'company_name' => 'Lançamentos Pro',
                'location' => 'Remoto',
                'type' => 'PJ',
                'level' => 'Especialista',
                'short_description' => 'Especialista em criar VSLs, páginas de vendas e sequências de e-mails que convertem estranhos em clientes.',
                'description' => '<h3>Foco</h3><p>Escrita persuasiva baseada em gatilhos mentais e psicologia de vendas.</p>',
                'requirements' => '<ul><li>Experiência com lançamentos (Fórmula de Lançamento)</li><li>Conhecimento em Storytelling</li></ul>',
                'benefits' => '<ul><li>Trabalho remoto</li><li>Participação no lucro dos lançamentos</li></ul>',
                'salary_range' => 'R$ 5.000,00 fixo + %',
                'visibility' => 'public',
                'is_active' => true,
                'is_demo' => true,
                'expires_at' => now()->addDays(20),
            ],
            [
                'title' => 'Analista de RH (Recrutamento e Seleção)',
                'company_name' => 'RH Consultoria',
                'location' => 'Porto Alegre, RS',
                'type' => 'CLT',
                'level' => 'Pleno',
                'short_description' => 'Responsável por triagem, entrevistas e processos admissionais de novos talentos.',
                'description' => '<h3>Papel</h3><p>Garantir que os novos colaboradores estejam alinhados com a cultura da empresa.</p>',
                'requirements' => '<ul><li>Formação em Psicologia ou RH</li><li>Experiência em recrutamento tech</li></ul>',
                'benefits' => '<ul><li>Plano de saúde</li><li>Seguro de vida</li></ul>',
                'salary_range' => 'R$ 4.500,00',
                'visibility' => 'public',
                'is_active' => true,
                'is_demo' => true,
                'expires_at' => now()->addDays(30),
            ],
            [
                'title' => 'Editor de Vídeos (Short Form)',
                'company_name' => 'Mídia Digital',
                'location' => 'Remoto',
                'type' => 'Freelance',
                'level' => 'Pleno',
                'short_description' => 'Edição dinâmica de vídeos para TikTok, Reels e Shorts com legendas e efeitos sonoros.',
                'description' => '<h3>Job</h3><p>Receber brutos e transformar em conteúdo viral de alto engajamento.</p>',
                'requirements' => '<ul><li>Domínio de Adobe Premiere ou CapCut (Pro)</li><li>Agilidade de entrega</li></ul>',
                'benefits' => '<ul><li>Pagamento por pack de vídeos</li></ul>',
                'salary_range' => 'R$ 150,00 / vídeo',
                'visibility' => 'public',
                'is_active' => true,
                'is_demo' => true,
                'expires_at' => now()->addDays(15),
            ],
            [
                'title' => 'Gerente de Projetos (Agile)',
                'company_name' => 'Tech Leads',
                'location' => 'São Paulo, SP (Híbrido)',
                'type' => 'CLT',
                'level' => 'Sênior',
                'short_description' => 'Facilitar o trabalho dos times de desenvolvimento utilizando Scrum e Kanban.',
                'description' => '<h3>Metodologia</h3><p>Organizar sprints, retrospectivas e garantir a entrega de valor contínua.</p>',
                'requirements' => '<ul><li>Certificação Scrum Master</li><li>Uso de Jira</li></ul>',
                'benefits' => '<ul><li>Bônus anual</li><li>Previdência privada</li></ul>',
                'salary_range' => 'R$ 11.000,00',
                'visibility' => 'public',
                'is_active' => true,
                'is_demo' => true,
                'expires_at' => now()->addDays(35),
            ],
            [
                'title' => 'Cientista de Dados Júnior',
                'company_name' => 'Data Intelligence',
                'location' => 'Remoto',
                'type' => 'PJ',
                'level' => 'Júnior',
                'short_description' => 'Análise de grandes volumes de dados para geração de insights e modelos preditivos simples.',
                'description' => '<h3>Atuação</h3><p>Limpeza de dados, criação de visualizações e suporte ao time de Data Science.</p>',
                'requirements' => '<ul><li>Python (Pandas, Numpy)</li><li>SQL</li><li>Power BI / Tableau</li></ul>',
                'benefits' => '<ul><li>Cultura de inovação</li><li>Horário flexível</li></ul>',
                'salary_range' => 'R$ 4.000,00',
                'visibility' => 'public',
                'is_active' => true,
                'is_demo' => true,
                'expires_at' => now()->addDays(25),
            ],
            [
                'title' => 'Analista de Marketing Digital',
                'company_name' => 'Growth Corp',
                'location' => 'Recife, PE (Híbrido)',
                'type' => 'CLT',
                'level' => 'Pleno',
                'short_description' => 'Execução de estratégias de inbound marketing, e-mail marketing e automação.',
                'description' => '<h3>Rotina</h3><p>Criar réguas de relacionamento e campanhas de nutrição de leads.</p>',
                'requirements' => '<ul><li>Conhecimento em RD Station ou HubSpot</li><li>Noções de SEO</li></ul>',
                'benefits' => '<ul><li>Gympass</li><li>Auxílio educação</li></ul>',
                'salary_range' => 'R$ 5.200,00',
                'visibility' => 'public',
                'is_active' => true,
                'is_demo' => true,
                'expires_at' => now()->addDays(30),
            ],
            [
                'title' => 'Suporte Técnico de TI',
                'company_name' => 'Infra Solutions',
                'location' => 'Fortaleza, CE',
                'type' => 'CLT',
                'level' => 'Júnior',
                'short_description' => 'Manutenção de hardware, redes e suporte aos usuários internos da empresa.',
                'description' => '<h3>Suporte</h3><p>Garantir que toda a estrutura tecnológica da empresa esteja operante.</p>',
                'requirements' => '<ul><li>Conhecimento de Windows/Linux</li><li>Configuração de redes</li></ul>',
                'benefits' => '<ul><li>Vale refeição</li><li>Plano odontológico</li></ul>',
                'salary_range' => 'R$ 2.800,00',
                'visibility' => 'public',
                'is_active' => true,
                'is_demo' => true,
                'expires_at' => now()->addDays(20),
            ],
        ];

        foreach ($vagas as $vaga) {
            $vaga['user_id'] = $admin->id;
            JobVacancy::create($vaga);
        }
    }
}
