<div class="grid grid-cols-6 gap-2 text-lg text-center">
    <button type="button" class="emoji-item" data-category="faces" data-emoji="😀">😀</button>
    <button type="button" class="emoji-item" data-category="faces" data-emoji="😁">😁</button>
    <button type="button" class="emoji-item" data-category="faces" data-emoji="😂">😂</button>
    <button type="button" class="emoji-item" data-category="faces" data-emoji="😅">😅</button>
    <button type="button" class="emoji-item" data-category="faces" data-emoji="🤣">🤣</button>
    <button type="button" class="emoji-item" data-category="faces" data-emoji="😍">😍</button>
    <button type="button" class="emoji-item" data-category="faces" data-emoji="😘">😘</button>
    <button type="button" class="emoji-item" data-category="faces" data-emoji="😎">😎</button>
    <button type="button" class="emoji-item" data-category="faces" data-emoji="🤩">🤩</button>
    <button type="button" class="emoji-item" data-category="faces" data-emoji="😇">😇</button>
    <button type="button" class="emoji-item" data-category="faces" data-emoji="🙂">🙂</button>
    <button type="button" class="emoji-item" data-category="faces" data-emoji="😉">😉</button>
    <button type="button" class="emoji-item" data-category="faces" data-emoji="😮">😮</button>
    <button type="button" class="emoji-item" data-category="faces" data-emoji="😲">😲</button>
    <button type="button" class="emoji-item" data-category="faces" data-emoji="😢">😢</button>
    <button type="button" class="emoji-item" data-category="faces" data-emoji="😭">😭</button>
    <button type="button" class="emoji-item" data-category="faces" data-emoji="😡">😡</button>
    <button type="button" class="emoji-item" data-category="faces" data-emoji="🤯">🤯</button>
    <button type="button" class="emoji-item" data-category="faces" data-emoji="😴">😴</button>
    <button type="button" class="emoji-item" data-category="faces" data-emoji="🤗">🤗</button>
    <button type="button" class="emoji-item" data-category="gestures" data-emoji="👍">👍</button>
    <button type="button" class="emoji-item" data-category="gestures" data-emoji="👎">👎</button>
    <button type="button" class="emoji-item" data-category="gestures" data-emoji="👏">👏</button>
    <button type="button" class="emoji-item" data-category="gestures" data-emoji="🙌">🙌</button>
    <button type="button" class="emoji-item" data-category="gestures" data-emoji="🙏">🙏</button>
    <button type="button" class="emoji-item" data-category="gestures" data-emoji="💪">💪</button>
    <button type="button" class="emoji-item" data-category="gestures" data-emoji="🤝">🤝</button>
    <button type="button" class="emoji-item" data-category="gestures" data-emoji="👌">👌</button>
    <button type="button" class="emoji-item" data-category="gestures" data-emoji="✌️">✌️</button>
    <button type="button" class="emoji-item" data-category="gestures" data-emoji="🤟">🤟</button>
    <button type="button" class="emoji-item" data-category="objects" data-emoji="🎉">🎉</button>
    <button type="button" class="emoji-item" data-category="objects" data-emoji="🎯">🎯</button>
    <button type="button" class="emoji-item" data-category="objects" data-emoji="🎁">🎁</button>
    <button type="button" class="emoji-item" data-category="objects" data-emoji="🏆">🏆</button>
    <button type="button" class="emoji-item" data-category="objects" data-emoji="📌">📌</button>
    <button type="button" class="emoji-item" data-category="objects" data-emoji="🧠">🧠</button>
    <button type="button" class="emoji-item" data-category="objects" data-emoji="💡">💡</button>
    <button type="button" class="emoji-item" data-category="objects" data-emoji="📣">📣</button>
    <button type="button" class="emoji-item" data-category="objects" data-emoji="🚀">🚀</button>
    <button type="button" class="emoji-item" data-category="objects" data-emoji="💼">💼</button>
    <button type="button" class="emoji-item" data-category="nature" data-emoji="🌿">🌿</button>
    <button type="button" class="emoji-item" data-category="nature" data-emoji="🌞">🌞</button>
    <button type="button" class="emoji-item" data-category="nature" data-emoji="🌈">🌈</button>
    <button type="button" class="emoji-item" data-category="nature" data-emoji="🌊">🌊</button>
    <button type="button" class="emoji-item" data-category="nature" data-emoji="🍀">🍀</button>
    <button type="button" class="emoji-item" data-category="nature" data-emoji="🌻">🌻</button>
    <button type="button" class="emoji-item" data-category="nature" data-emoji="🔥">🔥</button>
    <button type="button" class="emoji-item" data-category="nature" data-emoji="✨">✨</button>
    <button type="button" class="emoji-item" data-category="symbols" data-emoji="❤️">❤️</button>
    <button type="button" class="emoji-item" data-category="symbols" data-emoji="💙">💙</button>
    <button type="button" class="emoji-item" data-category="symbols" data-emoji="💚">💚</button>
    <button type="button" class="emoji-item" data-category="symbols" data-emoji="💛">💛</button>
    <button type="button" class="emoji-item" data-category="symbols" data-emoji="🧡">🧡</button>
    <button type="button" class="emoji-item" data-category="symbols" data-emoji="💜">💜</button>
    <button type="button" class="emoji-item" data-category="symbols" data-emoji="⭐">⭐</button>
    <button type="button" class="emoji-item" data-category="symbols" data-emoji="✅">✅</button>
</div>
