<?php

return [
    'commands' => [
        'Sistema' => [
            'cron:heartbeat' => 'Monitoramento do scheduler',
            'dashboard:warm-cache' => 'Aquecer cache das dashboards',
            'notifications:cleanup' => 'Limpeza de notificacoes',
            'logs:cleanup' => 'Limpeza/rotacao de logs',
            'auth:clear-resets' => 'Limpar tokens de senha',
            'sanctum:prune-expired' => 'Limpar tokens de API',
        ],
        'Filas' => [
            'emails:process-queue' => 'Processar fila de e-mails',
            'queue:work --stop-when-empty --tries=3 --timeout=120' => 'Processar fila geral',
        ],
        'Pedidos e Vendas' => [
            'sumup:reconcile-pending --limit=100' => 'Conciliar pedidos SumUp pendentes',
            'orders:send-unpaid-reminders --limit=200' => 'Lembretes de pedidos nao pagos',
            'orders:cancel-unpaid' => 'Cancelar pedidos nao pagos',
            'abandoned-cart:send' => 'Disparo de carrinho abandonado',
            'invoices:send-overdue-reminders' => 'Lembretes de faturas em atraso',
            'feedback:request-daily' => 'Solicitar feedback de compradores',
        ],
        'Conteudo e Membros' => [
            'lessons:process-pending-videos --limit=2' => 'Processar videos pendentes',
            'points:award-top-ranking' => 'Pontuar top ranking semanal',
            'points:award-birthday-bonus' => 'Pontuar aniversariantes',
            'share-requests:expire' => 'Expirar solicitacoes de compartilhamento',
            'redemptions:check-expired' => 'Verificar resgates expirados',
            'cart:cleanup-expired' => 'Limpar carrinho expirado',
            'subscriptions:check-expired' => 'Verificar assinaturas expiradas',
            'users:send-birthday-emails' => 'Enviar e-mails de aniversario',
            'events:update-batches' => 'Atualizar lotes de eventos',
            'reputation:recalculate' => 'Recalcular reputacao dos membros',
        ],
        'Seguranca' => [
            'waf:check-spike' => 'Verificar picos do WAF',
            'waf:purge-events' => 'Limpar eventos expirados do WAF',
            'waf:purge-ips' => 'Limpar IPs expirados do WAF',
        ],
        'Backups' => [
            'backup:database' => 'Backup do banco de dados',
            'backup:config' => 'Backup de configuracoes',
        ],
    ],

    'defaults' => [
        ['command' => 'cron:heartbeat', 'frequency' => '* * * * *', 'active' => true],
        ['command' => 'emails:process-queue', 'frequency' => '* * * * *', 'active' => true],
        ['command' => 'queue:work --stop-when-empty --tries=3 --timeout=120', 'frequency' => '* * * * *', 'active' => true],
        ['command' => 'lessons:process-pending-videos --limit=2', 'frequency' => '* * * * *', 'active' => true],
        ['command' => 'points:award-top-ranking', 'frequency' => '5 0 * * 0', 'active' => true],
        ['command' => 'points:award-birthday-bonus', 'frequency' => '0 1 * * *', 'active' => true],
        ['command' => 'share-requests:expire', 'frequency' => '0 2 * * *', 'active' => true],
        ['command' => 'dashboard:warm-cache', 'frequency' => '*/5 * * * *', 'active' => true],
        ['command' => 'sumup:reconcile-pending --limit=100', 'frequency' => '*/5 * * * *', 'active' => true],
        ['command' => 'orders:send-unpaid-reminders --limit=200', 'frequency' => '*/15 * * * *', 'active' => true],
        ['command' => 'orders:cancel-unpaid', 'frequency' => '*/5 * * * *', 'active' => true],
        ['command' => 'redemptions:check-expired', 'frequency' => '0 * * * *', 'active' => true],
        ['command' => 'cart:cleanup-expired', 'frequency' => '0 * * * *', 'active' => true],
        ['command' => 'subscriptions:check-expired', 'frequency' => '0 6 * * *', 'active' => true],
        ['command' => 'users:send-birthday-emails', 'frequency' => '0 7 * * *', 'active' => true],
        ['command' => 'invoices:send-overdue-reminders', 'frequency' => '0 8 * * *', 'active' => true],
        ['command' => 'events:update-batches', 'frequency' => '*/15 * * * *', 'active' => true],
        ['command' => 'waf:check-spike', 'frequency' => '*/5 * * * *', 'active' => true],
        ['command' => 'waf:purge-events', 'frequency' => '0 4 * * *', 'active' => true],
        ['command' => 'waf:purge-ips', 'frequency' => '15 4 * * *', 'active' => true],
        ['command' => 'abandoned-cart:send', 'frequency' => '0 */4 * * *', 'active' => true],
        ['command' => 'notifications:cleanup', 'frequency' => '0 3 * * *', 'active' => true],
        ['command' => 'feedback:request-daily', 'frequency' => '0 9 * * *', 'active' => true],
        ['command' => 'logs:cleanup', 'frequency' => '0 2 * * *', 'active' => true],
        ['command' => 'reputation:recalculate', 'frequency' => '0 0 * * *', 'active' => true],
        ['command' => 'backup:database', 'frequency' => '0 3 * * *', 'active' => true],
        ['command' => 'backup:config', 'frequency' => '0 4 * * 0', 'active' => true],
    ],
];
