version: '3.8'
services:
  app:
    image: php:8.2-fpm
    container_name: unn_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - unn-network
    depends_on:
      - db
  webserver:
    image: nginx:stable-alpine
    container_name: unn_web
    ports:
      - '8001:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - unn-network
    depends_on:
      - app
  db:
    image: mysql:8.0
    container_name: unn_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: unn
      MYSQL_USER: unn
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - '3307:3306'
    networks:
      - unn-network

volumes:
  dbdata:

networks:
  unn-network:
    driver: bridge
